db:
  image: postgres
  environment:
   - POSTGRES_HOST_AUTH_METHOD=trust

uwsgi:
  restart: always
  image: spack/spackmon
  volumes:
    - .:/code
    - ./static:/var/www/static
    - ./images:/var/www/images
  links:
    - redis

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./nginx/uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
  links:
    - uwsgi
